### ISSUE TITLE
Internal webPages are not responding

### ISSUE THREAD

**Issue by NaderElghamry** [sohip-a/Foodies#55]
After registering i have tried to open another page like(my account) and didnt respond and showed me the attached error

![Error](https://user-images.githubusercontent.com/123865763/231207902-dc04a822-b334-4d4c-b361-7e5b0c047ffa.png)

**Comment by AbdullahRamadan60** [comment]
The issue if fixed in commit  **# 5ad5db0a388071fad5f956ed49b8af455db4d708**

**Comment by AbdullahRamadan60** [comment]
The issue if fixed in commit **# 5ad5db0a388071fad5f956ed49b8af455db4d708**
